[project]
name = "better-auth-jwt"
version = "0.1.0"
description = "Better Auth JWT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.121.0",
    "pyjwt[cryptography]>=2.8.0",
    "python-dotenv>=1.0.0",
    "httpx>=0.27.0",
    "cryptography>=46.0.3",
]
